/* Generated By:JavaCC: Do not edit this line. SACParserConstants.java */
package com.steadystate.css.parser;

public interface SACParserConstants {

  int EOF = 0;
  int S = 1;
  int SINGLE_LINE_COMMENT = 5;
  int LBRACE = 6;
  int RBRACE = 7;
  int COMMA = 8;
  int DOT = 9;
  int SEMICOLON = 10;
  int COLON = 11;
  int ASTERISK = 12;
  int SLASH = 13;
  int PLUS = 14;
  int MINUS = 15;
  int EQUALS = 16;
  int GT = 17;
  int LSQUARE = 18;
  int RSQUARE = 19;
  int HASH = 20;
  int STRING = 21;
  int RROUND = 22;
  int URL = 23;
  int URI = 24;
  int CDO = 25;
  int CDC = 26;
  int INCLUDES = 27;
  int DASHMATCH = 28;
  int IMPORT_SYM = 29;
  int PAGE_SYM = 30;
  int MEDIA_SYM = 31;
  int FONT_FACE_SYM = 32;
  int CHARSET_SYM = 33;
  int ATKEYWORD = 34;
  int IMPORTANT_SYM = 35;
  int INHERIT = 36;
  int EMS = 37;
  int EXS = 38;
  int LENGTH_PX = 39;
  int LENGTH_CM = 40;
  int LENGTH_MM = 41;
  int LENGTH_IN = 42;
  int LENGTH_PT = 43;
  int LENGTH_PC = 44;
  int ANGLE_DEG = 45;
  int ANGLE_RAD = 46;
  int ANGLE_GRAD = 47;
  int TIME_MS = 48;
  int TIME_S = 49;
  int FREQ_HZ = 50;
  int FREQ_KHZ = 51;
  int DIMEN = 52;
  int PERCENTAGE = 53;
  int NUMBER = 54;
  int RGB = 55;
  int FUNCTION = 56;
  int IDENT = 57;
  int NAME = 58;
  int NUM = 59;
  int UNICODERANGE = 60;
  int RANGE = 61;
  int Q16 = 62;
  int Q15 = 63;
  int Q14 = 64;
  int Q13 = 65;
  int Q12 = 66;
  int Q11 = 67;
  int NMSTART = 68;
  int NMCHAR = 69;
  int STRING1 = 70;
  int STRING2 = 71;
  int NONASCII = 72;
  int ESCAPE = 73;
  int NL = 74;
  int UNICODE = 75;
  int HNUM = 76;
  int H = 77;
  int UNKNOWN = 78;

  int DEFAULT = 0;
  int COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 4>",
    "<SINGLE_LINE_COMMENT>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "<HASH>",
    "<STRING>",
    "\")\"",
    "<URL>",
    "<URI>",
    "\"<!--\"",
    "\"-->\"",
    "\"~=\"",
    "\"|=\"",
    "\"@import\"",
    "\"@page\"",
    "\"@media\"",
    "\"@font-face\"",
    "\"@charset\"",
    "<ATKEYWORD>",
    "<IMPORTANT_SYM>",
    "\"inherit\"",
    "<EMS>",
    "<EXS>",
    "<LENGTH_PX>",
    "<LENGTH_CM>",
    "<LENGTH_MM>",
    "<LENGTH_IN>",
    "<LENGTH_PT>",
    "<LENGTH_PC>",
    "<ANGLE_DEG>",
    "<ANGLE_RAD>",
    "<ANGLE_GRAD>",
    "<TIME_MS>",
    "<TIME_S>",
    "<FREQ_HZ>",
    "<FREQ_KHZ>",
    "<DIMEN>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "\"rgb(\"",
    "<FUNCTION>",
    "<IDENT>",
    "<NAME>",
    "<NUM>",
    "<UNICODERANGE>",
    "<RANGE>",
    "<Q16>",
    "<Q15>",
    "<Q14>",
    "<Q13>",
    "<Q12>",
    "\"?\"",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRING1>",
    "<STRING2>",
    "<NONASCII>",
    "<ESCAPE>",
    "<NL>",
    "<UNICODE>",
    "<HNUM>",
    "<H>",
    "<UNKNOWN>",
  };

}
